//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Installations = new HashSet<Installation>();
            this.Maintenance_FollowUp = new HashSet<Maintenance_FollowUp>();
            this.Maintenance_Visit = new HashSet<Maintenance_Visit>();
            this.Projects = new HashSet<Project>();
        }
    
        public long ID { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Telephone { get; set; }
        public string Customer_Address { get; set; }
        public int City_ID { get; set; }
        public string Referer1_Name { get; set; }
        public string Referer1_Telephone { get; set; }
        public string Referer2_Name { get; set; }
        public string Referer2_Telephone { get; set; }
        public string Referer3_Name { get; set; }
        public string Referer3_Telephone { get; set; }
        public string Referer4_Name { get; set; }
        public string Referer4_Telephone { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public Nullable<decimal> CustomerLocation { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installation> Installations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_FollowUp> Maintenance_FollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Visit> Maintenance_Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}
