//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installation()
        {
            this.Maintenance_FollowUp = new HashSet<Maintenance_FollowUp>();
            this.Maintenance_Visit = new HashSet<Maintenance_Visit>();
        }
    
        public long ID { get; set; }
        public long Customer_ID { get; set; }
        public int Product_ID { get; set; }
        public System.DateTime Installation_Date { get; set; }
        public decimal Count1 { get; set; }
        public int Capacity1_ID { get; set; }
        public Nullable<decimal> Count2 { get; set; }
        public Nullable<int> Capacity2_ID { get; set; }
        public Nullable<decimal> Count3 { get; set; }
        public Nullable<int> Capacity3_ID { get; set; }
        public Nullable<decimal> Count4 { get; set; }
        public Nullable<int> Capacity4_ID { get; set; }
        public Nullable<decimal> Count5 { get; set; }
        public Nullable<int> Capacity5_ID { get; set; }
        public string Comments { get; set; }
        public byte Maintenance_Type { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Capacity Capacity { get; set; }
        public virtual Capacity Capacity1 { get; set; }
        public virtual Capacity Capacity2 { get; set; }
        public virtual Capacity Capacity3 { get; set; }
        public virtual Capacity Capacity4 { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_FollowUp> Maintenance_FollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Visit> Maintenance_Visit { get; set; }
    }
}
