//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string TaskTitle { get; set; }
        public string Taskdec { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> TechId { get; set; }
        public System.DateTime Startat { get; set; }
        public System.DateTime Endat { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
