//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechRequest
    {
        public int RequestId { get; set; }
        public string RequestTiTle { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> RquestTime { get; set; }
        public string ReplyTiTle { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
